# Default values for app-stack.
# This is a YAML-formatted file.
# Declare variables to be substituted into your templates.

global:
  environment: production
  region: eu-central-1

# Application configuration
app:
  name: nebulance-app
  version: "1.0.0"
  
# Frontend configuration
frontend:
  name: frontend
  replicas: 2
  image:
    repository: nksusn/nebulance-app
    tag: "frontend-1.0.0"
    pullPolicy: IfNotPresent
  
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

# Backend configuration
backend:
  name: backend
  replicas: 3
  image:
    repository: nksusn/nebulance-app
    tag: "backend-1.0.0"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 20
    targetCPUUtilizationPercentage: 70
  
  env:
    NODE_ENV: production
    PORT: "3000"
    POSTGRES_HOST: postgres
    POSTGRES_PORT: "5432"

# Database configuration
database:
  name: postgres
  replicas: 1
  image:
    repository: postgres
    tag: "15-alpine"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
  
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  
  persistence:
    enabled: true
    storageClass: "gp3-csi"
    accessMode: ReadWriteOnce
    size: 20Gi

# Storage Class configuration
storageClass:
  enabled: true
  name: "gp3-csi"
  type: "gp3"
  iops: "3000"
  throughput: "125"
  encrypted: "true"

# AWS Secrets Manager integration
secrets:
  enabled: true
  region: eu-central-1
  secretStore:
    name: aws-secrets-store
    serviceAccountName: external-secrets
    namespace: external-secrets

  database:
    secretName: database-secrets
    secretPath: "eks-app/database"
    keys:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  application:
    secretName: application-secrets
    secretPath: "eks-app/application"
    keys:
      - JWT_SECRET
      - API_KEY
      - NODE_ENV

# LoadBalancer configuration (replaces Ingress)
loadbalancer:
  enabled: true
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

# Service account for IRSA
serviceAccount:
  create: true
  name: external-secrets-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::940482433884:role/eks-nebulance-external-secrets"

# Monitoring and observability
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s

# Security context (applied per service as needed)
securityContext:
  runAsNonRoot: true
  fsGroup: 2000

# Node selection
nodeSelector: {}

tolerations: []

affinity: {}
