{{- if .Values.secrets.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.database.secretName }}
  namespace: {{ .Values.app.name }}
  labels:
    {{- include "app-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.secrets.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.secrets.database.secretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secrets.database.secretPath }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.application.secretName }}
  namespace: {{ .Values.app.name }}
  labels:
    {{- include "app-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.secrets.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.secrets.application.secretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secrets.application.secretPath }}
{{- end }}
