apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.app.name }}
  labels:
    name: {{ .Values.app.name }}
    app.kubernetes.io/name: {{ include "app-stack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    description: "Namespace for the {{ .Values.app.name }} application stack"