{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secrets.secretStore.name }}
  namespace: {{ .Values.app.name }}
  labels:
    {{- include "app-stack.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secrets.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secrets.secretStore.serviceAccountName }}
{{- end }}